---
- name: install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
  tags:
    - lighthouse

- name: install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start nginx service
  tags:
    - lighthouse

- name: Disable SELinux
  become: true
  ansible.posix.selinux:
    state: disabled
  tags:
    - lighthouse
  notify: setenforce


- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ lighthouse_location_dir }}"
    state: directory
    mode: '0755'
  tags:
    - lighthouse

- name: install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
  tags:
    - lighthouse

- name: copy lighthouse service from git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: /tmp/lighthouse
  tags:
    - lighthouse



- name: copy lighthouse files1 to nginx workdir
  become: true
  ansible.builtin.copy:
    src: "/tmp/lighthouse/{{ item }}"
    dest: "{{ lighthouse_location_dir }}"
    mode: '0644'
    remote_src: true
    follow: true
  loop:
    - js
    - app.js
    - index.html
    - jquery.js
  notify: restart nginx service
  tags:
    - lighthouse

- name: copy lighthouse files2 to nginx workdir
  become: true
  ansible.builtin.copy:
    src: "/tmp/lighthouse/{{ item }}"
    dest: "{{ lighthouse_location_dir }}"
    mode: '0751'
    remote_src: true
    follow: true
  loop:
    - css
    - img
  notify: restart nginx service
  tags:
    - lighthouse

- name: create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: '0644'
  notify: restart nginx service
  tags:
    - lighthouse
