---
- name: start nginx service
  become: true
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
- name: restart nginx service
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted
- name: setenforce
  become: true
  command: setenforce 0
